### ISSUE TITLE
Commits are duplicated on update

### ISSUE THREAD

**Issue by anxolerd** [notwaldorf/tiny-terminal-care#1]
## Description

When the dashboard updated, my commits were duplicated. So instead of 15 commits I've got 30.

## STR

1. (for convenience) change the update interval to 5 seconds
2. set up several directories which have projects
3. run dashboard
4. wait for update to happen (5 seconds according to step 1)
5. Observe the result

## Actual result

Commits were duplicated, and instead of my honest 13 commits for today I see 26 commits :| That is weird.

## Expected result

I still see my honest 13 commits.

## GIF
![tiny-terminal-care](https://cloud.githubusercontent.com/assets/6533582/25066525/b6275ee2-2230-11e7-979b-834282e0ebbc.gif)

## Environment

```
% node -v
v6.10.0
% npm -v
3.10.10
```

**Comment by notwaldorf** [comment]
Makes sense! This isn't really ready for use -- I'm still trying to figure out npm, but if you wanna send me that as a PR i'll merge it! :)
